language: node_js

node_js:
  - "v10.18.1"
  - "v12.14.1"
  - "v13.7.0"

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - node_modules

jobs:
  include:
    # Fix hanging Windows tests (because of yarn):
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    - node_js: "v10.18.1"
      os: windows
      env: YARN_GPG=no
    - node_js: "v12.14.1"
      os: windows
      env: YARN_GPG=no
    - node_js: "v13.7.0"
      os: windows
      env: YARN_GPG=no

script:
  - yarn test --coverage --silent
after_script:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      # Push tests coverage data to Coveralls:
      - ./node_modules/.bin/coveralls < ./coverage/lcov.info
      # Push tests coverage data to Codecov:
      - npx codecov
    fi

after_success:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -n "$TRAVIS_TAG" ]; then
      # Publish the package on npm
      bash scripts/ci/deploy.sh
    fi

branches:
  only:
  - develop
  - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f6c7fbd99c6425464bbc
    on_cancel: change
    on_error: always
    on_failure: always
    on_start: change
    on_success: change
